package Model;
// Generated 09-May-2020 08:29:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bookscategory generated by hbm2java
 */
public class Bookscategory  implements java.io.Serializable {


     private int categoryId;
     private String categoryName;
     private Set bookses = new HashSet(0);

    public Bookscategory() {
    }

	
    public Bookscategory(int categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Bookscategory(int categoryId, String categoryName, Set bookses) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.bookses = bookses;
    }
   
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getBookses() {
        return this.bookses;
    }
    
    public void setBookses(Set bookses) {
        this.bookses = bookses;
    }




}


