package Model;
// Generated 09-May-2020 08:29:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private int id;
     private Bookscategory bookscategory;
     private String title;
     private String publishingHouse;
     private Date publicationDate;
     private String author;
     private int pages;

    public Books() {
    }

    public Books(int id, Bookscategory bookscategory, String title, String publishingHouse, Date publicationDate, String author, int pages) {
       this.id = id;
       this.bookscategory = bookscategory;
       this.title = title;
       this.publishingHouse = publishingHouse;
       this.publicationDate = publicationDate;
       this.author = author;
       this.pages = pages;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Bookscategory getBookscategory() {
        return this.bookscategory;
    }
    
    public void setBookscategory(Bookscategory bookscategory) {
        this.bookscategory = bookscategory;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPublishingHouse() {
        return this.publishingHouse;
    }
    
    public void setPublishingHouse(String publishingHouse) {
        this.publishingHouse = publishingHouse;
    }
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public int getPages() {
        return this.pages;
    }
    
    public void setPages(int pages) {
        this.pages = pages;
    }




}


