package Model;
// Generated 09-May-2020 08:29:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable {


     private Integer id;
     private int clientId;
     private String bookName;
     private String author;
     private String status;
     private Date returnDate;

    public Operation() {
    }

    public Operation(int clientId, String bookName, String author, String status, Date returnDate) {
       this.clientId = clientId;
       this.bookName = bookName;
       this.author = author;
       this.status = status;
       this.returnDate = returnDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getClientId() {
        return this.clientId;
    }
    
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }




}


